apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-claim
  namespace: development
spec:
  storageClassName: my-shared-pv
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi