apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: frankhul/log-output:v0.3
          env:
          - name: PORT
            value: "4002"
          - name: PING_PONG_ENDPOINT
            value: "http://ping-pong-svc:2345"