apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: frankhul/todo-backend:v0.3
          env:
          - name: PORT
            value: "4001"
          resources:
            limits:
              cpu: "200m"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: "/todo-backend/todos"
              port: 4001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: "/todo-backend/todos"
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10